name: Daily Quote & Commits

on:
  schedule:
    - cron: '15 6 * * *'  
  workflow_dispatch:        
  # for manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Run script
        env:
          API_NINJAS_KEY: ${{ secrets.API_NINJAS_KEY }}
        run: |
          chmod +x script.sh
          ./script.sh

      - name: Push changes
        run: git push
